quarkus:
  datasource:
    db-kind: mysql
    reactive:
      url: mysql://192.168.10.200:3306/beasts_evolved_console?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true
    username: root
    password: 123456
